Name = input('Vul hier je naam in: ')    
Adres = input('Vul hier je adres in: ')
Postcode = input('Vul hier je postcode in: ')
Woonplaats = input('Vul hier je woonplaats in: ')

print(' ----------------------------------------------------')
print(' |  Naam      : ' + str(Name)                         )
print(' |  Adres     : ' + str(Adres)                        )
print(' |  Postcode  : ' + str(Postcode)                     )
print(' |  Woonplaats: ' + str(Woonplaats)                   )
print(' ----------------------------------------------------')